firmware: fix AttributeError when update_local_firmware is called with a string
digidotcom/xbee-python pull request #294
Opened 2023-12-13 19:51 UTC by mikewadsten

This finally block assumed that target was always an XBeeDevice, while all of the code above it did the right thing and properly handled the case of it being a str.

Without this fix, performing a local update using a serial port argument will error out here with

    AttributeError: 'str' object has no attribute '_active_update_type'

2023-12-13 19:54 UTC, mikewadsten commented on digi/xbee/firmware.py
> +            else True
I'm not 100% sure if this is the right thing to claim for a direct serial-port update. Would this be better?

    else (msg == 'Success')

2023-12-18 09:22 UTC, tatianaleon requested changes

2023-12-18 18:02 UTC, mikewadsten commented on digi/xbee/firmware.py
> +            else True
I'm fine with rewriting the `finished` variable as you've put it here. The end result is exactly the same, the only difference is really whether we're checking for `isinstance(target, str)` or `isinstance(target, XBeeDevice)`.

And good catch on line 7134. I'll make that change.

2023-12-19 09:50 UTC, daescalona approved these changes

2023-12-19 10:21 UTC, tatianaleon approved these changes

2023-12-19 15:23 UTC, merged